### ISSUE TITLE
search n-grams by shift-clicking

### ISSUE THREAD

**Issue by g-w1** [Saptak625/Quizolytics#4]
Hello. First of all, thank you so much for making this amazing app! It is quite useful and my friends also find it useful.

One feature that I would like is a way to search the n-grams as answer line by shift-clicking on them. I know that just regular clicking on them copies them, and this is probably good, but I'd also want to search them separately to see when they show up as answer lines.

Thanks!

**Comment by Saptak625** [comment]
Hi @g-w1! I am happy to hear that my app is useful to people.

If I understand your request, you would like Shift + Click on an n-gram to open a new tab with the answerline. Could you provide an instance where you think this functionality could be useful?

I appreciate your feedback.

**Comment by g-w1** [comment]
Sorry, I think you might understand me wrong. I was probably unclear.

I would like Shift + Click (or Ctrl + Click) on an n-gram to open **a new tab with that n-gram as the query to analyze**. This would allow me to see how common n-grams are not only as clues, but also as answerlines in a really smooth way. It basically gives me a graph to traverse and study. I can keep control-clicking to go deeper down the rabbit hole. Kind of like wikipedia links where when you click it, it opens up the page with that as the query and other stuff as the n-grams.

**Comment by g-w1** [comment]
From what I can read of your code, you should be able to construct a new POST request in javascript that opens in a new tab something like this:
```js
function postRedirectNewTab(url, data) {
    var form = document.createElement('form');
    document.body.appendChild(form);
    form.method = 'post';
    form.action = url;
    form.target = '_blank'; // This opens the form submission in a new tab

    for (var name in data) {
        var input = document.createElement('input');
        input.type = 'hidden';
        input.name = name;
        input.value = data[name];
        form.appendChild(input);
    }

    form.submit();
}

postRedirectNewTab('http://example.com', { key1: 'value1', key2: 'value2' });
```
Then you just need to intercept the onclick and instead of immediately copying, check if shift is pressed first.

**Comment by Saptak625** [comment]
@g-w1 The feature has been implemented in [4db6810](https://github.com/Saptak625/Quizolytics/commit/4db68106ababa6328a1586b9d2ba7958f59649c3). To minimize new tab load and compute times, shift-clicking just creates a new tab with the n-gram as the query. This also enables users to change the difficulty and categories searching before executing an analysis.

If you think your enhancement request has been satisfied, please close this issue. Thank you.

**Comment by g-w1** [comment]
This seems like it would work, but the website: https://quizolytics.vercel.app/analyze is not updated, but that seems like something that is out of the scope of this issue.

I'm closing, thanks! If it doesn't work once the website is updated I'll re-open.

**Comment by Saptak625** [comment]
@g-w1 Vercel project was deploying. Should be good now.

**Comment by g-w1** [comment]
This works great! Thanks!
